data: add support for ELAN-2AD9 in HP ProBook x360 435 G7
linuxwacom/libwacom pull request #418
Opened 2021-08-01 02:40 UTC by ganthern

2021-08-01 22:16 UTC, whot requested changes
Two minor requests, but looks good otherwise, thanks.

2021-08-01 22:16 UTC, whot commented on data/elan-2ad9.tablet
> +DeviceMatch=i2c:04f3:2AD9
vid and pid need to be lowercase hex

2021-08-01 22:16 UTC, whot commented on data/elan-2ad9.tablet
> +# ELAN touchscreen/pen sensor in the HP Probook x360 435 G7
can you submit your sysinfo to https://github.com/linuxwacom/wacom-hid-descriptors/ and link to it here please. Will help with future debugging of the device.

2021-08-02 08:56 UTC, ganthern commented
Sysinfo at https://github.com/linuxwacom/wacom-hid-descriptors/issues/165

2021-08-03 03:24 UTC, whot commented on data/elan-2ad9.tablet
> +
```suggestion
#
# sysinfo.9FNnwQKhog
# https://github.com/linuxwacom/wacom-hid-descriptors/issues/165

```

2021-08-03 03:31 UTC, merged

2021-08-03 03:32 UTC, whot commented
Thanks, I updated the file with the full link (through the github UI, let's hope that didn't screw things up). All merged now