Add ASUS ROG Flow X16
linuxwacom/libwacom pull request #524
Opened 2022-09-22 08:59 UTC by somnathb1

2022-11-17 00:57 UTC, whot requested changes
Thanks for the PR. Please make sure you submit the `sysinfo` tarball and add/link to it in the file here. See the [wiki](https://github.com/linuxwacom/libwacom/wiki/Tablet-Definition-Files) for details and/or [a recent commit](https://github.com/linuxwacom/libwacom/commit/dfc3c9a454ebb37cc4a613727ce8a141fe99a211).

2023-01-19 22:55 UTC, whot commented
ping?

2023-01-20 18:33 UTC, somnathb1 commented
> ping?

Hi, sorry for the delay, I will submit it by tomorrow

2023-01-23 05:08 UTC, whot approved these changes

2023-01-23 05:08 UTC, whot commented on data/elan-2fc2.tablet
> +# Auto generated sysinfo file
```suggestion
# Auto generated sysinfo file
# sysinfo.layqUCS31O
```

2023-01-23 05:16 UTC, merged

2023-01-23 05:16 UTC, whot commented
Merged with a minor fix, thanks!