Generate the class given in class if not explicitly given (libwacom#790)
linuxwacom/libwacom pull request #792
Opened 2024-10-16 21:51 UTC by redstrate

This is still a part of the API, and thus have required even new .tablet files to fill this out even though it's superseded by IntegratedIn. So let's generate them programmatically.

This turns devices that are IntegratedIn=Display to the Cintiq class, IntegratedIn=Display;System into the ISDV4 class, and everything else into the Bamboo class.

(This definitely needs more test cases)

2024-10-17 10:44 UTC, whot requested changes
One minor style nitpick but this LGTM.

For the test cases - remove it from the `.tablet` files for the few other devices we hand-check in `test-load` and I think we'll be good there?

2024-10-17 10:44 UTC, whot commented on libwacom/libwacom.c
> +	}
```suggestion
	unsigned int flags = device->integration_flags & (WACOM_DEVICE_INTEGRATED_DISPLAY|WACOM_DEVICE_INTEGRATED_SYSTEM);
	
	if (flags == (WACOM_DEVICE_INTEGRATED_DISPLAY|WACOM_DEVICE_INTEGRATED_SYSTEM)) {
		return WCLASS_ISDV4;
	}
	if (flags == WACOM_DEVICE_INTEGRATED_DISPLAY) {
		return WCLASS_CINTIQ;
	}
```
is i think a bit more readable. 

(oh, and I always like to have `()` around any bitwise operations, it makes the code a bit more readable)

2024-10-17 10:44 UTC, whot commented on libwacom/libwacom.c
> +	return WCLASS_BAMBOO;
I think the `Remote` class is missing here, that will need handling, could go together with #779.

Then again there's so few of them that we can mark those in the `.tablet` file...

2024-10-21 03:57 UTC, whot commented on libwacom/libwacom.c
> +	return WCLASS_BAMBOO;
Oh, come to think of it: this is better as `WCLASS_INTUOS5` - that's the most recent class and most devices are more like that than whatever the latest bamboo was like.

2024-10-28 06:09 UTC, whot commented
@redstrate ok if I take this one and push it over the line?

2024-10-28 12:09 UTC, redstrate commented
Yes go ahead, I don’t have access to a computer right now and would appreciate it :)On Oct 27, 2024, at 23:09, Peter Hutterer ***@***.***> wrote:﻿
@redstrate ok if I take this one and push it over the line?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-10-29 01:21 UTC, whot commented on libwacom/libwacom.c
> +	return WCLASS_BAMBOO;
For the archives: `WCLASS_BAMBOO` is better here because bamboos arent' expected to have stylus ids/serials.

2024-10-29 01:29 UTC, whot commented
Thanks, closing in favour of #814 now

2024-10-29 01:29 UTC, closed without merging