Create wacom-hid-52c6.tablet
linuxwacom/libwacom pull request #795
Opened 2024-10-17 13:16 UTC by chrostino

since the `sysinfo.sh` script was unable to generate the `.tablet` file I wrote this manually following instructions and copying from files of similar devices, although I am unsure if the `ModelName=` field needs to be filled (I left it blank since I couldn't find that information) and don't know if the line `Styli=@isdv4-aes` is even necessary. Some of the files of other devices I looked at had it, some didn't.
Also I believed there was a problem in the file I discussed in #794, but closed the issue since I it is fixed by #793

2024-10-18 00:01 UTC, whot requested changes
Thanks, this is mostly good but I'll need you to fix the commit messsage, see e.g. 9a36f7666e04cd49c8ecc438c18840bb04a4743f for the most recent one. It doesn't need to have a lot of info unless there's something really special about the device.

2024-10-18 00:02 UTC, whot commented
`ModelName` can be left blank, and for the `Styli` line: run `tools/show-stylus.py` and see what that says. If it doesn't see any stylus IDs you can leave it out, otherwise what you have will be fine.

2024-10-18 10:01 UTC, chrostino commented
> `ModelName` can be left blank, and for the `Styli` line: run `tools/show-stylus.py` and see what that says. If it doesn't see any stylus IDs you can leave it out, otherwise what you have will be fine.

it shows the two stylus I have, the lenovo digital pen 2 and the lenovo precision pen 2 (2023), both of which still need to be merged in their pull requests (that I have added to my `/etc/libwacom/wacom.stylus`
Also after terminating in the terminal it shows this
```
Unknown stylus id 0x0. New entry needed
Suggested line for .tablet file:
Styli=isdv4-aes
```
should I just put `Styli=@isdv4-aes`?

2024-10-21 03:41 UTC, whot commented on data/wacom-hid-52c6.tablet
> +DeviceMatch=i2c:056a:52c6;
```suggestion
DeviceMatch=i2c|056a|52c6;
```

2024-10-21 03:46 UTC, merged

2024-10-21 03:47 UTC, whot commented
squashed and merged, thanks. Now that there's multiple commits I could even fix the commit message :)

`isdv4-aes` is fine, thanks