Support "AliasOf" keyword
linuxwacom/libwacom pull request #844
Opened 2024-12-24 21:13 UTC by skomra

Add a new keyword to libwacom.stylus so we can share the settings among those tools that of the same type: RFC: stylus tool id aliases.

https://github.com/linuxwacom/libwacom/issues/761

2025-01-06 08:56 UTC, whot requested changes
Thanks for the patches - overall looks good with a few minor code changes. As for the actual stylus file: I think we should be minimally aggressive on using the aliases, especially for old and discontinued hw where it's just easier to not ever touch this again.

2025-01-06 08:56 UTC, whot commented on libwacom/libwacom-database.c
> +		    const char *key, const char *fallback) {
```suggestion
		    const char *key, const char *fallback) 
		    {
```
including the others below too please

2025-01-06 08:56 UTC, whot commented on libwacom/libwacom-database.c
> +		 const char *key, bool fallback, WacomStylus *stylus) {
looks like indentation is off here and in the `int_or_fallback` too

2025-01-06 08:56 UTC, whot commented on libwacom/libwacom-database.c
> +	values = g_new (gchar *, array->len + 1);
```suggestion
	values = g_new0 (gchar *, array->len + 1);
```
saves you manually null-terminating it a few lines below. Having said that - we're already using glib here so this could probably be something like:
```c

g_autoptr(GArray) *a = g_array_new(true, false, array->len);
for (...) {
   g_array_append_vals(...)
}
return g_array_steal(a);
```

2025-01-06 08:56 UTC, whot commented on libwacom/libwacom-database.c
> +        }
up to here we have the same code from `parse_stylus_id`, we should be able to use that and then override `id->tool_id` with just the aliased int. I think...

better than having the parsing code duplicated.

2025-01-06 08:56 UTC, whot commented on libwacom/libwacom-database.c
> +		}
```suggestion
		g_autofree char *aliasstr = g_key_file_get_string(keyfile, groups[i], "AliasOf", NULL);
		if (alias == IGNORE_ALIASES && aliasstr) {
			continue;
		}

		if (alias == ONLY_ALIASES && !aliasstr) {
			continue;
		}
```
because there's no point doing `g_key_file_get_string()` three times for an alias

2025-01-06 08:56 UTC, whot commented on libwacom/libwacom-database.c
> +libwacom_parse_stylus_keyfile(WacomDeviceDatabase *db, const char *path, AliasStatus alias)
nitpick:

```suggestion
libwacom_parse_stylus_keyfile(WacomDeviceDatabase *db, const char *path, AliasStatus handle_aliases)
```
might make this more immediately understandable (and lets you use `alias` for the actual alias)

2025-01-06 08:56 UTC, whot commented on libwacom/libwacom-database.c
> +			if (!create_stylus_id_from_aliased(groups[i], alias_value, &lookup)) {
nickpick on the name:
```suggestion
			if (!create_stylus_id_from_alias(groups[i], alias_value, &lookup)) {
```

2025-01-06 08:56 UTC, whot commented on libwacom/libwacom-database.c
> +			string_list = g_key_file_get_string_list(keyfile, groups[i], "PairedStylusIds", NULL, NULL);
```suggestion
		string_list = g_key_file_get_string_list(keyfile, groups[i], "PairedStylusIds", NULL, NULL);
		if (alias != IGNORE_ALIASES) {
```
does the same thing I think

2025-01-06 08:56 UTC, whot commented on libwacom/libwacom-database.c
> +
```suggestion
```

2025-01-06 08:56 UTC, whot commented on libwacom/libwacom-database.c
> +		libwacom_parse_stylus_keyfile(db, path, alias);
heh, see my comment above for immediately readable by naming to `handle_aliases` because I looked at this and was wondering why we're passing an alias into the keyfile parser

2025-01-06 08:56 UTC, whot commented on libwacom/util-strings.h
> +}
i know this feels pointless but can we add some test cases for this so we never have to worry about this again?

Arguably a `switch` on the base could look nicer but I'm not going to die on that particular hill :)

2025-01-06 08:56 UTC, whot commented on libwacom/libwacom-database.c
> +		values[i] = strdup(buffer);
`safe_itoa_base` always returns true so the `ret` assignment is pointless (and we don't check it here anyway). But since this is appears to be the only place we need it we can skip that helper altogether and make it a:

```suggestion
		values[i] = g_strdup_printf("0x%08x", id->tool_id);
```

2025-01-06 08:56 UTC, whot commented on libwacom/libwacom-database.c
> +		WacomStylusId id, lookup;
Move `lookup` into the condition where we use it please, makes the code more obvious.

2025-01-06 08:56 UTC, whot commented on libwacom/libwacom-database.c
> +		WacomStylus *stylus, *other;
Is there a word like `aliasee`? Or maybe `source_stylus`? Or some other word that tells us immediately that this is the one we're aliasing to (from?).

2025-01-06 08:56 UTC, whot commented on libwacom/libwacom-database.c
> +	g_autoptr(GError) local_error = NULL;
Regarding the use of `g_autoptr` see my comment in https://github.com/linuxwacom/libwacom/issues/142#issuecomment-2290465558 - I think right now scan-build is more useful to us than g_autoptr/g_autofree so as annoying as it is we should do these manually.

I've used it in my suggestions below but only because it's easier to type out here than adding the correct free lines, so please adjust for that

2025-01-06 08:56 UTC, whot commented on data/wacom.stylus
> +AliasOf=0x1
ack to all these since they seem to be the same hw

2025-01-06 08:56 UTC, whot commented on data/wacom.stylus
> +AliasOf=0x20802
Is this really worth changing these? The I2 is now old enough that we should never have to think about it again so leaving this code untouched forever is better. This applies to a whole bunch of others too, IMO using aliases is best for where it's really "same thing, different id" even though the alias implementation lets us almost use it like CSS.

2025-02-06 23:22 UTC, whot commented on libwacom/libwacom-database.c
> +	return g_array_steal(a, (long unsigned int *)(&(a->len)));
That cast can have interesting side-effects if `sizeof(a->len) != sizeof(long unsigned int)`, an easier way around this is:

```suggestion
	gsize len = a->len;
	return g_array_steal(a, len);
```

2025-02-06 23:23 UTC, whot commented on libwacom/libwacom-database.c
> +garray_to_string_list(GArray *array)
this sounds like it's a generic array->string list conversion but it's a `WacomStylusId` -> hex string converstion, let's rename this please, e.g. 

```
stylus_ids_as_hex(GArray *array)
```
or something similar

2025-02-10 20:32 UTC, skomra commented on libwacom/libwacom-database.c
> +	return g_array_steal(a, (long unsigned int *)(&(a->len)));
That is giving me the following error. I'm not sure why g_array_steal wants a pointer. 
```
../libwacom/libwacom-database.c: In function ‘stylus_ids_as_hex’:
../libwacom/libwacom-database.c:397:33: error: passing argument 2 of ‘g_array_steal’ makes pointer from integer without a cast [-Wint-conversion]
  397 |         return g_array_steal(a, len);
      |                                 ^~~
      |                                 |
      |                                 gsize {aka long unsigned int}
In file included from /usr/include/glib-2.0/glib.h:33,
                 from ../libwacom/libwacomint.h:34,
                 from ../libwacom/libwacom-database.c:30:
/usr/include/glib-2.0/glib/garray.h:86:54: note: expected ‘gsize *’ {aka ‘long unsigned int *’} but argument is of type ‘gsize’ {aka ‘long unsigned int’}
   86 |                                    gsize            *len);
      |                                    ~~~~~~~~~~~~~~~~~~^~~
```

2025-02-10 23:40 UTC, whot commented on libwacom/libwacom-database.c
> +	return g_array_steal(a, (long unsigned int *)(&(a->len)));
Edited my suggestion above  - you can pass `&len` instead but after checking the source for `g_array_steal()` - len is an output-only argument and returns the number of elements in the array, we can pass NULL since we don't care about that value here.

2025-02-11 00:16 UTC, whot commented on libwacom/libwacom-database.c
> +		return NULL;
```suggestion
	if (array == NULL || array->len == 0)
		return NULL;
```
to avoid
```
not ok /load/0000:0000 - GLib-FATAL-CRITICAL: g_array_new: assertion 'elt_size > 0' failed
```

2025-02-11 00:16 UTC, whot commented on libwacom/libwacom-database.c
> +		char *aliasstr = g_key_file_get_string(keyfile, groups[i], "AliasOf", NULL);
Note that `aliasstr` leaks in every `continue` case below (except the `!aliasstr` one)

2025-02-11 00:16 UTC, whot commented on libwacom/libwacom-database.c
>  		stylus->id = id;
You're allocating `stylus` here but it's not used until after the `g_clear_pointer(aliasstr)` line - any `continue` between here and later will leak `stylus` - IOW move those three lines down past the aliasstr handling (or rather, don't add all the new code above `g_new0` :)

2025-02-12 00:58 UTC, skomra commented
I needed to run the full check on the code changes so I pushed the first patch. I'm still working on the updated data file.

2025-02-13 04:51 UTC, whot commented
> I needed to run the full check on the code changes so I pushed the first patch. I'm still working on the updated data file.

what I sometimes do is to `git switch -c somebranch-v2`, then work on that and push it (without filing an MR but looking at the `Actions` in github) and when it finally passes I move the patches over to the `somebranch` (cherry-pick or git reset) and push that to the already-open PR. This way it's less embarrassing for me when I have to play trial-and-error with the CI because no-one sees the pushes :)

2025-02-13 21:17 UTC, skomra commented
Thanks for the tip! I think I used to do that but I haven't been active on github in a while and had forgotten that.

The data file patch has been added and the PR is ready for review again. Thanks for your help.

2025-02-17 01:26 UTC, whot commented on libwacom/libwacom-database.c
> +			g_clear_pointer(&aliasstr, g_free);
not really necessary since we explicitly check for it to be NULL but it doesn't hurt and makes it more symmetric I guess.

2025-02-17 01:26 UTC, whot commented on libwacom/libwacom-database.c
> +				continue;
both of the `continue`s here will leak `stylus`.

You could trigger this with a crafted `StylusEntry` in `test_libwacom.py` but since we don't run those tests in valgrind.... :shrug:

2025-02-17 01:26 UTC, whot commented on libwacom/libwacom-database.c
> +		stylus->name = string_or_fallback(keyfile, groups[i], "Name", aliased ? aliased->name : NULL, NULL);
If you move the `stylus = g_new0` lines to here you don't need to worry about a leaking `stylus` above

2025-02-17 01:26 UTC, whot commented on libwacom/libwacom-database.c
> +		if (handle_aliases != IGNORE_ALIASES) {
```suggestion
		if (handle_aliases == ONLY_ALIASES) {
```
we only have two values, might as well check for the explicit one

2025-02-17 01:26 UTC, whot commented on libwacom/libwacom-database.c
> +		stylus->num_buttons = int_or_fallback(keyfile, groups[i], "Buttons", aliased ? aliased->num_buttons : 0, error);
I keep thinking that for the alias is null case:
```
WacomStylus empty = {0};
WacomStylus *aliased = &empty;
```
then you don't need all the `aliased ? aliased->foo : 0` conditions.

2025-02-17 01:26 UTC, whot commented on libwacom/libwacom-database.c
> +		if (handle_aliases == ONLY_ALIASES && (string_list == NULL)) {
```suggestion
		if (handle_aliases == ONLY_ALIASES && string_list == NULL) {
```

2025-02-17 01:26 UTC, whot commented on libwacom/libwacom-database.c
> +			}
```suggestion
				}
```

2025-02-17 01:26 UTC, whot commented on libwacom/libwacom.h
> +} AliasStatus;
This one must not be in `libwacom.h`, otherwise it becomes public API. Just putting it into `libwacom-database.c` is enough, it's not used anywhere else.

2025-03-17 01:18 UTC, whot requested changes
a few nitpicks regarding style but the biggest issue here is that there's still a memleak on some of the error paths

2025-03-17 01:18 UTC, whot commented on libwacom/libwacom-database.c
> +		g_array_append_vals(a, g_strdup_printf("0x%08x", id->tool_id), 1);
see related comment below: best to append the vendor id here too to make this a full stylus id in the form `0x1234:0xabcd`

2025-03-18 00:53 UTC, whot commented on libwacom/libwacom-database.c
> +				g_warning ("Failed to parse Aliased ID '%s', ignoring entry", groups[i]);
staring at this again: this check is superflous since we unconditionally check the parsing of `groups[i]` about 20 lines north of here anyway.

2025-03-18 21:40 UTC, skomra commented on libwacom/libwacom-database.c
> +				g_warning ("Failed to parse Aliased ID '%s', ignoring entry", groups[i]);
Hi Peter, You mention above that "there's still a memleak on some of the error paths" (plural) but I think line 454 is the only memleak you mention in your comments here. Is there a second memleak besides this one?

2025-03-18 21:41 UTC, skomra commented on libwacom/libwacom-database.c
> +		g_array_append_vals(a, g_strdup_printf("0x%08x", id->tool_id), 1);
The way this appeared, it is your last comment. So by below I think you're referring to the comment right above this, just double checking that I understand you right.

2025-03-18 21:49 UTC, skomra commented on libwacom/libwacom-database.c
> +		g_array_append_vals(a, g_strdup_printf("0x%08x", id->tool_id), 1);
I just noticed #871 - so you can ignore the comments I just made. Sorry about that I was going through my mail oldest to newest.

2025-03-21 01:00 UTC, whot commented
Superseded by #871

2025-03-21 01:00 UTC, closed without merging